# Generated by Django 5.2.2 on 2025-10-17 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_invoice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 17, 15, 57, 26, 212464, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
