# Generated by Django 5.2.2 on 2025-10-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_businessprofile_remove_sale_date_alter_sale_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='change_due',
            new_name='balance_due',
        ),
    ]
