# Generated by Django 5.2.2 on 2025-10-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_change_due_invoice_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Invoiced', 'Invoiced')], default='Pending', max_length=10),
        ),
    ]
