# Generated by Django 5.2.2 on 2025-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='override_product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='override_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
