# Generated by Django 5.2.2 on 2025-10-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_sale_cash_received_sale_discount_sale_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
