# Generated by Django 5.2.2 on 2025-10-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sale_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
