# Generated by Django 5.2.2 on 2025-11-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_sale_customer_name_sale_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscredential',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='accesscredential',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
