# Generated by Django 5.2.2 on 2025-11-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_accesscredential_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscredential',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accesscredential',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
    ]
